name: my_university
description: تطبيق جدول المحاضرات الأسبوعي
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2         

  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_local_notifications: ^16.1.0
  android_alarm_manager_plus: ^3.0.2
  provider: ^6.0.5
  flutter_slidable: ^3.0.1
  url_launcher: ^6.1.14
  flutter_native_splash: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
